// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj_kplUzi9kAHOOszUgWnYtd0YHLw-6WA',
    appId: '1:371609333904:web:02734adc1c9e2155a92815',
    messagingSenderId: '371609333904',
    projectId: 'fir-cli-3e270',
    authDomain: 'fir-cli-3e270.firebaseapp.com',
    storageBucket: 'fir-cli-3e270.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDARyn3suyiGsFxSSAcircc-Hh0IabzscU',
    appId: '1:371609333904:android:deca24118887039ea92815',
    messagingSenderId: '371609333904',
    projectId: 'fir-cli-3e270',
    storageBucket: 'fir-cli-3e270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjpSK-q19pQSlNgM-3vr8YjVNt9LAUl4',
    appId: '1:371609333904:ios:357daa2eebd42c6aa92815',
    messagingSenderId: '371609333904',
    projectId: 'fir-cli-3e270',
    storageBucket: 'fir-cli-3e270.appspot.com',
    iosBundleId: 'com.example.pawsupunf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjpSK-q19pQSlNgM-3vr8YjVNt9LAUl4',
    appId: '1:371609333904:ios:357daa2eebd42c6aa92815',
    messagingSenderId: '371609333904',
    projectId: 'fir-cli-3e270',
    storageBucket: 'fir-cli-3e270.appspot.com',
    iosBundleId: 'com.example.pawsupunf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj_kplUzi9kAHOOszUgWnYtd0YHLw-6WA',
    appId: '1:371609333904:web:bdad0ee67c380182a92815',
    messagingSenderId: '371609333904',
    projectId: 'fir-cli-3e270',
    authDomain: 'fir-cli-3e270.firebaseapp.com',
    storageBucket: 'fir-cli-3e270.appspot.com',
  );
}
